import type { Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
  SignOutButton
} from '@clerk/nextjs'
import { dark, neobrutalism  } from "@clerk/themes"
import { Geist, Geist_Mono, Inter, IBM_Plex_Mono } from "next/font/google";

import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const plexMono = IBM_Plex_Mono({
  variable: "--font-plex-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
     theme: [dark, neobrutalism],
      }}
    >
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${inter.variable} ${plexMono.variable} antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <br></br>
            <SignedOut>
              <div className="flex gap-2">

                <SignInButton>
                  <button className="bg-blue-500 text-white px-4 py-2 rounded-md">Waapas aja</button>
                </SignInButton>
                <SignUpButton>
                  <button className="bg-green-500 text-white px-4 py-2 rounded-md">Naya bana le</button>
                </SignUpButton>
              </div>
            </SignedOut>
            <SignedIn>
              <UserButton></UserButton>
              <SignOutButton>
                <button>Chala ja</button>
              </SignOutButton>
            </SignedIn>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
